#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct  5 22:11:29 2021

@author: akkatung
"""
print('AK Bank ยินดีต้อนรับครับ\nกำลังเข้าสู่ระบบการรับฝากเงิน....\nทางธนาคารของเรารับฝากเงินโดยคิดดอกเบี้ยทบต้นที่ร้อยละ 3 บาทต่อปี')
ip = input('กรุณากรอกจำนวนเงินต้นและระยะเวลาที่ฝาก(ปี) : ') 
pv,year =ip.split()
fv=int(pv)
interrest=int(pv)
for i in range(int(year)):
    fv+=int(pv)*0.03
    pv=fv
print('ภายในระยเวลา',year,'ปี ท่านได้รับดอกเบี้ยทั้งสิ้น',fv-interrest,'บาท เมื่่อรวมกับเงินต้นจะเท่ากับ',fv,'บาท')